# Generated by Django 2.2.19 on 2022-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220913_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.URLField(),
        ),
    ]
